### PR TITLE
Fixes "No submodule mapping" error

### PR DESCRIPTION
**Pull request by cgilmour**
Clears out an error "No submodule mapping found" for a submodule we're not using anymore.

```sh-session
cgilmour@cg-macbookpro:$GOPATH/src/github.com/romana/core$ git submodule update --init
No submodule mapping found in .gitmodules for path 'vendor/github.com/nabeken/negroni-auth'
cgilmour@cg-macbookpro:$GOPATH/src/github.com/romana/core$ git rm --cached 'vendor/github.com/nabeken/negroni-auth'
rm 'vendor/github.com/nabeken/negroni-auth'
cgilmour@cg-macbookpro:$GOPATH/src/github.com/romana/core$ git submodule update --init
cgilmour@cg-macbookpro:$GOPATH/src/github.com/romana/core$ go build github.com/romana/core/...
cgilmour@cg-macbookpro:$GOPATH/src/github.com/romana/core$ go install github.com/romana/core/...
cgilmour@cg-macbookpro:$GOPATH/src/github.com/romana/core$ 
```

### CODE REVIEW

**Comment by pritesh** [comment]
actually we are using it, i thought the same but realized it is in @debedb 's next commit here: https://github.com/romana/core/commit/5a94c7678bd6eb84491422738e4d689e62ad9393

**Comment by cgilmour** [comment]
I can't see it actually used by any code.
Greg mentioned it was vendored but then later removed.
Somehow partial references stuck around somewhere.

**Comment by pritesh** [comment]
sounds good, we may have to update #43 , it still has some partial reference.

**Comment by pritesh** [comment]
Looks good to me.

**Comment by debedb** [comment]
You both right - it was used in a branch, then I realized it's useless, removed it. However- with the new Go vendoring being the way to go in 1.6 - and this issue - how do we want to deal with it?

I used to have a script to deal with it (like https://gist.github.com/debedb/cc4971e03f5321c289ad but I think that's out of date).

**Pull request merged**
